export const SUB_COUNTY_MAPPINGS = [
  {
    county_id: "1",
    county_name: "MOMBASA",
    sub_counties: {
      Changamwe: ["Port Reitz", "Kipevu", "Airport", "Changamwe", "Chaani"],
      Nyali: ["Frere Town", "Ziwa la Ngombe", "Mkomani", "Kongowea", "Kadzandani"],
      Kisauni: ["Mjambere", "Junda", "Bamburi", "Mwakirunge", "Mtopanga", "Magogoni", "Shanzu"],
      Jomvu: ["Jomvu Kuu", "Miritini", "Mikindani"],
      Likoni: ["Mtongwe", "ShikaAdabu", "Bofu", "Likoni", "Timbwani"],
      Mvita: ["Mjiwa Kale/ Makadara", "Tudor", "Tononoka", "Majengo", "Ganjoni/ Shimanzi"],
    },
  },
  { county_id: "2", county_name: "KWALE" },
  { county_id: "3", county_name: "KILIFI" },
  { county_id: "4", county_name: "TANA RIVER" },
  { county_id: "5", county_name: "LAMU" },
  { county_id: "6", county_name: "TAITA TAVETA" },
  { county_id: "7", county_name: "GARISSA" },
  { county_id: "8", county_name: "WAJIR" },
  { county_id: "9", county_name: "MANDERA" },
  { county_id: "10", county_name: "MARSABIT" },
  { county_id: "11", county_name: "ISIOLO" },
  { county_id: "12", county_name: "MERU" },
  { county_id: "13", county_name: "THARAKA-NITHI" },
  { county_id: "14", county_name: "EMBU" },
  { county_id: "15", county_name: "KITUI" },
  { county_id: "16", county_name: "MACHAKOS" },
  { county_id: "17", county_name: "MAKUENI" },
  { county_id: "18", county_name: "NYANDARUA" },
  { county_id: "19", county_name: "NYERI" },
  { county_id: "20", county_name: "KIRINYAGA" },
  { county_id: "21", county_name: "MURANG'A" },
  {
    county_id: "22",
    county_name: "KIAMBU",
    sub_counties: {
      "Gatundu North": ["Gituamba", "Githobokoni", "Chania", "Mang’u"],
      "Gatundu South": ["Kiamwangi", "Kiganjo", "Ndarugo", "Ngenda"],
      Githunguri: ["Githunguri", "Githiga", "Ikinu", "Ngewa", "Komothai"],
      Juja: ["Murera", "Theta", "Juja", "Witeithie", "Kalimoni"],
      Kabete: ["Gitaru", "Muguga", "Nyathuna", "Kabete", "Uthiru"],
      Kiambaa: ["Cianda", "Karuri", "Ndenderu", "Muchatha", "Kihara"],
      Kiambu: ["Ting’ang’a", "Ndumberi", "Riabai", "Township"],
      Kikuyu: ["Karai", "Nachu", "Sigona", "Kikuyu", "Kinoo"],
      Lari: ["Kinale", "Kijabe", "Nyanduma", "Kamburu", "Lari/Kirenga"],
      Limuru: ["Bibirioni", "Limuru Central", "Ndeiya", "Limuru East", "Ngecha/Tigoni"],
      Ruiru: [
        "Gitothua",
        "Biashara",
        "Gatongora",
        "Kahawa/Sukari",
        "Kahawa Wendani",
        "Kiuu",
        "Mwiki",
        "Mwihoko",
      ],
      "Thika Town": ["Township", "Kamenu", "Hospital", "Gatuanyaga", "Ngoliba"],
    },
  },
  { county_id: "23", county_name: "TURKANA" },
  { county_id: "24", county_name: "WEST POKOT" },
  { county_id: "25", county_name: "SAMBURU" },
  { county_id: "26", county_name: "TRANS NZOIA" },
  { county_id: "27", county_name: "UASIN GISHU" },
  { county_id: "28", county_name: "ELGEYO/MARAKWET" },
  { county_id: "29", county_name: "NANDI" },
  { county_id: "30", county_name: "BARINGO" },
  { county_id: "31", county_name: "LAIKIPIA" },
  { county_id: "32", county_name: "NAKURU" },
  { county_id: "33", county_name: "NAROK" },
  { county_id: "34", county_name: "KAJIADO" },
  { county_id: "35", county_name: "KERICHO" },
  { county_id: "36", county_name: "BOMET" },
  { county_id: "37", county_name: "KAKAMEGA" },
  { county_id: "38", county_name: "VIHIGA" },
  { county_id: "39", county_name: "BUNGOMA" },
  { county_id: "40", county_name: "BUSIA" },
  { county_id: "41", county_name: "SIAYA" },
  { county_id: "42", county_name: "KISUMU" },
  { county_id: "43", county_name: "HOMA BAY" },
  { county_id: "44", county_name: "MIGORI" },
  { county_id: "45", county_name: "KISII" },
  { county_id: "46", county_name: "NYAMIRA" },
  { county_id: "47", county_name: "NAIROBI" },
];

